In [1]:
import numpy as np
import pandas as pd

In [2]:
pm_df=pd.read_csv("predictive_maintenance.csv")

In [3]:
pm_df

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0         1     M14860    M                298.1                    308.6   
1         2     L47181    L                298.2                    308.7   
2         3     L47182    L                298.1                    308.5   
3         4     L47183    L                298.2                    308.6   
4         5     L47184    L                298.2                    308.7   
...     ...        ...  ...                  ...                      ...   
9995   9996     M24855    M                298.8                    308.4   
9996   9997     H39410    H                298.9                    308.4   
9997   9998     M24857    M                299.0                    308.6   
9998   9999     H39412    H                299.0                    308.7   
9999  10000     M24859    M                299.0                    308.7   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target  \
0                       1551         42.8                0       0   
1                       1408         46.3                3       0   
2                       1498         49.4                5       0   
3                       1433         39.5                7       0   
4                       1408         40.0                9       0   
...                      ...          ...              ...     ...   
9995                    1604         29.5               14       0   
9996                    1632         31.8               17       0   
9997                    1645         33.4               22       0   
9998                    1408         48.5               25       0   
9999                    1500         40.2               30       0   

     Failure Type  
0      No Failure  
1      No Failure  
2      No Failure  
3      No Failure  
4      No Failure  
...           ...  
9995   No Failure  
9996   No Failure  
9997   No Failure  
9998   No Failure  
9999   No Failure  

[10000 rows x 10 columns]

In [5]:
#Independant Variable
x=pm_df.iloc[:,3:8].values
x

array([[ 298.1,  308.6, 1551. ,   42.8,    0. ],
       [ 298.2,  308.7, 1408. ,   46.3,    3. ],
       [ 298.1,  308.5, 1498. ,   49.4,    5. ],
       ...,
       [ 299. ,  308.6, 1645. ,   33.4,   22. ],
       [ 299. ,  308.7, 1408. ,   48.5,   25. ],
       [ 299. ,  308.7, 1500. ,   40.2,   30. ]])

In [9]:
#Dependant Variable(Target Variable)
y=pm_df.iloc[:,8]
y

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: Target, Length: 10000, dtype: int64

In [11]:
# now lets split the data into train and test
from sklearn.model_selection import train_test_split

# Splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=42)

In [12]:
## classifying

from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5,
                                       n_estimators=100, oob_score=True)

In [16]:
## fitting x & y train models

classifier_rf=classifier_rf.fit(X_train, y_train)
classifier_rf

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [17]:
## predicting y_pred
y_pred=classifier_rf.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [18]:
## checking the y_test
y_test

6252    0
4684    1
1731    0
4742    0
4521    0
       ..
8014    0
1074    0
3063    0
6487    0
4705    0
Name: Target, Length: 3000, dtype: int64

In [19]:
# Constructing the confusion matrix.

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[2903,    4],
       [  63,   30]], dtype=int64)

In [21]:
## Checking the accuracy of model

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9776666666666667
